import Head from 'next/head'
import Link from 'next/link'
import { CodeBlock, dracula } from "react-code-blocks";

import {apiHelloCode, apiEmojiCode, apiDogCode} from '../code/examples'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Next.js API Routes Examples 🚀</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Next.js API Routes Examples 🚀</h1>
      <p>
        Hi there! This is a playground to test out {" "}
        <a href="https://nextjs.org/docs/api-routes/introduction">Next.js API Routes</a>.
      </p>
      <p>
        You can browse the code for this site on {" "}
        <a href="https://github.com/khriztianmoreno/nextjs-api-routes">GitHub</a>.
      </p>

      <article>
        <h2>Hello, World!</h2>
        <p>The inevitable Hello World example.</p>
        <pre className="language-js">
          <CodeBlock
            text={apiHelloCode}
            language="javascript"
            showLineNumbers
            theme={dracula}
          />
        </pre>
        <h3>Try it out</h3>
        <p>
          <Link href="/api/hello">
            <a>Hello</a>
          </Link>
        </p>
      </article>

      <article>
        <h2>Random Emoji 🧪</h2>
        <p>Generating random emoji.</p>
        <pre className="language-js">
          <CodeBlock
            text={apiEmojiCode}
            language="javascript"
            showLineNumbers
            theme={dracula}
          />
        </pre>
        <h3>Try it out</h3>
        <p>
          <Link href="/api/emoji">
            <a>Emoji</a>
          </Link>
        </p>
      </article>

      <article>
        <h2>List 🐶 photos</h2>
        <p>Generating list dog photos.</p>
        <p>
          For this gallery, we will query a free Unsplash API to obtain super cute images of dogs and display them in a
          masonry.
          Head to Unsplash, signup to <a href="https://unsplash.com/developers" target="_blank" rel="noreferrer">create a new app and get an
            access key</a>.
        </p>
        <pre className="language-js">
          <CodeBlock
            text={apiDogCode}
            language="javascript"
            showLineNumbers
            theme={dracula}
          />
        </pre>
        <h3>Try it out</h3>
        <p>
          <Link href="/api/dog">
            <a>List 🐶 photos</a>
          </Link>
        </p>
      </article>

      <h2>👨🏼‍💻 Developed by <a href="https://khriztianmoreno.dev" target="_blank" rel="noopener noreferrer">khriztianmoreno</a></h2>
    </div>
  )
}
